// server/tools/markdownCompiler.js
// Compiles data from previous tools into formatted markdown reports saved to disk.

import fs from "fs/promises";
import path from "path";
import { PROJECT_ROOT } from "../utils/config.js";

export async function markdownCompiler(request) {
  const text = typeof request === "string" ? request : (request?.text || request?.input || "");
  const context = typeof request === "object" ? (request?.context || {}) : {};

  try {
    // 1. Check for Chain Context (Per CLAUDE.md Rules)
    let contentToCompile = "";
    if (context.chainContext?.previousOutput) {
      contentToCompile = String(context.chainContext.previousOutput);
    } else {
      return {
        tool: "markdownCompiler",
        success: false,
        final: true,
        error: "Action failed: No previous tool output found to compile. This tool must be used in a chain."
      };
    }

    // 2. Determine Filename
    // Extract a filename if the user specified one (e.g., "save this as competitor_analysis.md")
    let filename = "agent_report.md";
    const filenameMatch = text.match(/([\w-]+\.md)/i);
    if (filenameMatch) {
      filename = filenameMatch[1];
    } else {
      // Generate a timestamped name if none provided
      const dateStr = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      filename = `report_${dateStr}.md`;
    }

    // 3. Ensure Output Directory
    const outputDir = path.join(PROJECT_ROOT, "downloads");
    await fs.mkdir(outputDir, { recursive: true });
    const filePath = path.join(outputDir, filename);

    // 4. Format and Write File
    const header = `# Compiled Report\n*Generated by Agent on ${new Date().toLocaleString()}*\n\n---\n\n`;
    await fs.writeFile(filePath, header + contentToCompile, "utf8");

    return {
      tool: "markdownCompiler",
      success: true,
      final: true,
      data: {
        text: `📝 **Report Successfully Compiled**\n\nYour data has been saved to:\n\`${filePath}\``,
        preformatted: true
      }
    };

  } catch (error) {
    return {
      tool: "markdownCompiler",
      success: false,
      final: true,
      error: `Action failed: Could not compile report - ${error.message}`
    };
  }
}